apiVersion: v1
kind: Namespace
metadata:
  name: bmordoj
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: lab3-config
  namespace: bmordoj
data:
  USER_KEY: "lab3-user"
---
apiVersion: v1
kind: Secret
metadata:
  name: lab3-secret
  namespace: bmordoj
type: Opaque
data:
  BD_PASSWORD: cGFzc3dvcmQ=   # password base64
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab3-app
  namespace: bmordoj
spec:
  replicas: 3
  selector:
    matchLabels:
      app: lab3-app
  template:
    metadata:
      labels:
        app: lab3-app
    spec:
      containers:
        - name: lab3-app
          image: ghcr.io/benx1984/lab3-app:latest
          ports:
            - containerPort: 3000
          env:
            - name: USER_KEY
              valueFrom:
                configMapKeyRef:
                  name: lab3-config
                  key: USER_KEY
            - name: BD_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: lab3-secret
                  key: BD_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: lab3-service
  namespace: bmordoj
spec:
  selector:
    app: lab3-app
  ports:
    - port: 80
      targetPort: 3000
  type: NodePort